### ISSUE TITLE
Workflow CRD MVP

### ISSUE THREAD

**Issue by ngerakines** [ngerakines/k8s-workflow-deploy#6]
```yaml
apiVersion: workflow-deployer.ngerakines.me/v1alpha
kind: Workflow
metadata:
  name: Default
spec:
  namespaces: ["foo", "bar", "baz"]
  version: "v1.2.0"
  steps:
  - action: update
    targets:
    - resource: deployment/worker
      containers: ["app"]
    - resource: deployment/api
      containers: ["app"]
```
